=== CBOR schema

The schema for this type is defined by the `identity` rule in the following https://datatracker.ietf.org/doc/html/rfc8610[CDDL definition]:

:note-caption: Andrew
NOTE: It's conceivable that we could implement all the changes without ever requiring multiple signatures in a single identity assertion. 
You can always translate the enclosing credential into a valid signer_payload, so what if that's all we articulated, and the rest was in the signautre?
i.e. if you have a VC and a VP, you aggregate all the info from the VP and place the aggregate object in the credential.
If you have just a VC, you similarly aggregate all the info. 
Then it's just a matter of how we validate the signature and interpret the trust signals based on who has enclosed which information in their signature and to what degree you trust that person, which seems fine.

:note-caption: Note

[source,cddl]
----
include::schema.cddl[]
----

:note-caption: Andrew
NOTE: 1.1 is no longer a future minor version.

:note-caption: Note

IMPORTANT: Future minor version updates (1.1, 1.2, etc.) to this specification MAY add new fields to the `signer-payload-map` description, provided that such new data members are optional and there is a well-specified default meaning that is compatible with the 1.0 version of this specification.
Such updates to the specification SHOULD continue to use the `cawg.identity` assertion label.

Possible values for the `signer_payload.sig_type` field and the corresponding interpretations of the `signature` field are described in xref:_credentials_signatures_and_validation_methods[xrefstyle=full].

The `hashed-uri-map` rule is defined in link:++https://c2pa.org/specifications/specifications/1.3/specs/C2PA_Specification.html#_hashed_uris++[Section 8.3.1, “Hashed URIs,”] of the C2PA technical specification.

Possible values for the text string entries in the `signer_payload.role` field are provided in xref:_named_actor_roles[xrefstyle=full].

==== Example

An example in https://www.rfc-editor.org/rfc/rfc8949.html#name-diagnostic-notation[CBOR-Diag] is shown below, which is non-normative:

[source,json]
----
{
  "signer_payload": {
    "sig_type": "cawg.x509.cose",
    "referenced_assertions": [
      {
        "url": "self#jumbf=c2pa/urn:uuid:F9168C5E-CEB2-4faa-B6BF-329BF39FA1E4/c2pa.assertions/c2pa.hash.data",
        "hash": b64'U9Gyz05tmpftkoEYP6XYNsMnUbnS/KcktAg2vv7n1n8='
      },
      {
        "url": "self#jumbf=c2pa/urn:uuid:F9168C5E-CEB2-4faa-B6BF-329BF39FA1E4/c2pa.assertions/c2pa.thumbnail.claim.jpeg",
        "hash": b64'G5hfJwYeWTlflxOhmfCO9xDAK52aKQ+YbKNhRZeq92c='
      },
      {
        "url": "self#jumbf=c2pa/urn:uuid:F9168C5E-CEB2-4faa-B6BF-329BF39FA1E4/c2pa.assertions/c2pa.ingredient.v2",
        "hash": b64'Yzag4o5jO4xPyfANVtw7ETlbFSWZNfeM78qbSi8Abkk='
      }
    ],
    "role": ["cawg.creator"],
  },
  "signature": b64'....', // COSE signature
  "pad1": b64'....', // zero-filled pad buffer
  "pad2": b64'....'  // zero-filled pad buffer
}
----
