=== Overview

:note-caption: Andrew
NOTE: The "MAY" here is a bit confusing, as it seems to imply there are other non-disclosed things an identity assertion can do. Here's how I'd rewrite the section:
"This specification defines a C2PA assertion, called an identity assertion, that binds a named actor to a C2PA asset. 
It MAY reference other C2PA assertions and MAY include the named actor’s role in relation to the asset; the credential holder's signature SHALL represent their attestation to the accuracy of the information provided."

:note-caption: Note

This specification defines a _<<C2PA assertion>>_ known as an *<<_identity_assertion,identity assertion>>* which MAY be used to bind one _<<_named_actor,named actor>>_ to a set of _<<_referenced_assertions,referenced assertions>>_ and other related data, known overall as the _signer payload._
This binding SHOULD generally be construed as authorization of or participation in the creation of the statements described by those assertions and corresponding portions of the _<<C2PA asset>>_ in which they appear.

The *<<_identity_assertion,identity assertion>>* contains the following data fields:

* `signer_payload` contains the set of data to be signed by the _<<_credential_holder,credential holder>>_
* `signature` contains the raw byte stream of the _<<_credential_holder,credential holder>>’s_ signature
* `pad1` and `pad2` are byte strings filled with binary `0x00` values used to fill space

The `signer_payload` field is a structure of type `signer-payload-map` which is signed by the _<<_credential_holder,credential holder>>_.
It contains the following fields:

:note-caption: Andrew
NOTE: `role` might beed to be redefined to be "the _<<_named_actor,named actor’s>>_ relationship(s) to the _<<C2PA Manifest>>_ from the referenced hard binding assertion" as opposed to the _<<C2PA asset>>_.
The refined description here isn't perfect, but it's a start.
Separately, `expected_countersigners` might need some refinement to make it clear how it differs from the other reasons identity assertions may reference each other (e.g. delegation)

:note-caption: Note

* `referenced_assertions` _(required)_ is an array of `hashed-uri-map` structures with one entry for every _<<_referenced_assertions,referenced assertion>>_ chosen by the _<<_credential_holder,credential holder>>._
It is subject to several requirements as described in xref:_referenced_assertions_requirements[xrefstyle=full].
* `sig_type` _(required)_ is a string identifying the data type of the signature.
Valid credential types and the corresponding `signature` data structures and `signer_payload.sig_type` values are defined in xref:_credentials_signatures_and_validation_methods[xrefstyle=full].
* `role` _(optional)_ One or more values describing the _<<_named_actor,named actor’s>>_ function with respect to the _<<C2PA claim>>_ identified by a hard binding referenced by this identity assertion. 
A role value asserts the actor’s relationship to the asset state and the set of assertions sealed by that claim. Role values SHOULD be taken from xref:_named_actor_roles[xrefstyle=full]. 
A role claim applies only to that bound claim and SHALL NOT be construed as a role across other claims or asset versions.
* `expected_partial_claim` _(optional),_ if present, describes the content of the expected _<<C2PA claim>>,_ in which the *<<_identity_assertion,identity assertion>>* appears.
It can be used to prevent the introduction or removal of _<<_c2pa_assertion,C2PA assertions>>_ (other than the _<<_referenced_assertion,referenced assertions>>_) that could create unintended or unexpected semantics for the overall _<<C2PA Manifest>>._
The method for calculating this field is described in xref:_calculating_the_expected_partial_claim_field[xrefstyle=full].
* `expected_claim_generator` _(optional),_ if present, describes the X.509 certificate of the expected _<<C2PA claim generator>>._
It can be used to avoid creating an unwanted association between the _<<_named_actor,named actor>>_ and an unexpected or undesired _<<C2PA claim generator>>._
The method for calculating this field is described in xref:_calculating_the_expected_claim_generator_field[xrefstyle=full].
* `expected_countersigners` _(optional),_ if present, describes the content of other *<<_identity_assertion,identity assertion>>* in the same _<<C2PA Manifest>>._
The method for calculating this field is described in xref:_calculating_the_expected_countersigners_field[xrefstyle=full].

The *<<_identity_assertion,identity assertion>>* SHALL have a label of `cawg.identity`.

:note-caption: Andrew
NOTE: This is still true, but now incomplete. Multiple identity assertions can also be used to describe a single named actor as of PR3.

:note-caption: Note

Multiple identity assertions may be used in the same _<<C2PA Manifest>>_ to describe the distinct roles of multiple _<<_actor,actors>>_ in creating a single _<<C2PA asset>>._
This is illustrated in the xref:multiple-identity-assertions[multi-author example] from the conceptual overview.
If this occurs, these assertions SHALL be given unique labels as described by link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_multiple_instances++[Section 6.4, “Multiple instances,”] of the C2PA technical specification.

==== Referenced assertions requirements

The list of _<<_referenced_assertions,referenced assertions>>_ contained in `signer_payload.referenced_assertions` is subject to the following requirements:

* For each assertion listed, an assertion with the same `url`, `alg`, and `hash` values MUST also be listed in the `created_assertions`, `gathered_assertions`, or `assertions` field of the _<<C2PA claim>>_ in which the *<<_identity_assertion,identity assertion>>* appears.

NOTE: The `assertions` field appears only in version 1.x of the C2PA technical specification.
It was replaced with `created_assertions` and `gathered_assertions` in version 2.0 of the C2PA technical specification.

:note-caption: Andrew
NOTE: In the VP model, the consolidated list must include a hard binding, but it would be redundant to force the VP C2PAAssetBinding to include a hard binding if the VC C2PAAssetBinding already includes on.
What we probably want to do here is, in the new credential, define a consolidation of the referenced assertions that must satisfy these requirements.
If we do that, then it becomes reasonable for every C2PAAssetBinding to require a list of referenced assertions meeting these criteria (while still allowing for VCs that do not bind to a C2PA asset)

:note-caption: Note

* The list MUST NOT reference any assertion more than once.
* The list MUST include a _<<_hard_binding,hard binding>>_ assertion as described in link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_hard_bindings++[Section 9.2, “Hard bindings,”] of the C2PA technical specification.
* The list MAY reference other *<<_identity_assertion,identity assertions>>,* provided that no cycle of references among *<<_identity_assertion,identity assertions>>* is created.

NOTE: The requirement that the `hash` value for a _<<_referenced_assertions,referenced assertion>>_ be known prior to presenting `signer_payload` for signature implies that an *<<_identity_assertion,identity assertion>>* MUST NOT refer to itself.

==== Named actor roles

:note-caption: Andrew
NOTE: Same comment about a role not really binding to the entire C2PA Asset.

:note-caption: Note

The _<<_credential_holder,credential holder>>_ MAY choose to describe one or more relationships of the _<<_named_actor,named actor>>_ to the _<<C2PA asset>>_ by adding a `role` field to `signer_payload`.

If present, the value for `role` MUST be a non-empty CBOR array of non-empty text strings.
It is recommended that the CBOR text strings be chosen from the following values and that any user experience that presents the content of an *<<_identity_assertion,identity assertion>>* be prepared to describe these roles in the same human language as the surrounding interface:

[width="100%",cols="4,10",options="header"]
|=======================

| Value
| Meaning

| `cawg.creator`
| The _<<_named_actor,named actor>>_ is a primary creator/author of this _<<C2PA asset>>._

| `cawg.contributor`
| The _<<_named_actor,named actor>>_ is a secondary creator/author of this _<<C2PA asset>>._

| `cawg.editor`
| The _<<_named_actor,named actor>>_ is an editor of this _<<C2PA asset>>._

| `cawg.producer`
| The _<<_named_actor,named actor>>_ is a producer of this _<<C2PA asset>>._

| `cawg.publisher`
| The _<<_named_actor,named actor>>_ is a publisher of this _<<C2PA asset>>._

| `cawg.sponsor`
| The _<<_named_actor,named actor>>_ has supported or sponsored the creation of this _<<C2PA asset>>._

| `cawg.translator`
| The _<<_named_actor,named actor>>_ has adapted of this _<<C2PA asset>>_ from a similar work in another language.

|=======================

Other CBOR text string values MAY be used for `role`, subject to the restrictions described in xref:_labels[xrefstyle=full].
