=== Overview

This specification defines a _<<C2PA assertion>>_ known as an *<<_identity_assertion,identity assertion>>* which MAY be used to bind one _<<_named_actor,named actor>>_ to a set of _<<_referenced_assertions,referenced assertions>>_ and other related data, known overall as the _signer payload._
This binding SHOULD generally be construed as authorization of or participation in the creation of the statements described by those assertions and corresponding portions of the _<<C2PA asset>>_ in which they appear.

The *<<_identity_assertion,identity assertion>>* contains the following data fields:

* `signer_payload` contains the set of data to be signed by this _<<_credential_holder,credential holder>>_
* `signature` contains the raw byte stream of the _<<_credential_holder,credential holder>>’s_ signature
* `pad1` and `pad2` are byte strings filled with binary `0x00` values used to fill space

The `signer_payload` field is a structure of type `signer-payload-map` which is signed by the _<<_credential_holder,credential holder>>_.
It contains the following fields:

* `referenced_assertions` _(required)_ is an array of `hashed-uri-map` structures with one entry for every _<<_referenced_assertions,referenced assertion>>_ chosen by the _<<_credential_holder,credential holder>>._
It is subject to several requirements as described in xref:_referenced_assertions_requirements[xrefstyle=full].
* `sig_type` _(required)_ is a string identifying the data type of the signature.
Valid credential types and the corresponding `signature` data structures and `signer_payload.sig_type` values are defined in xref:_credentials_signatures_and_validation_methods[xrefstyle=full].
* `role` _(optional)_ contains one or more descriptions of the _<<_named_actor,named actor’s>>_ relationship(s) to the _<<C2PA asset>>._
Possible role values are described in xref:_named_actor_roles[xrefstyle=full].
* `expected_partial_claim` _(optional),_ if present, describes the content of the expected _<<C2PA claim>>,_ in which the *<<_identity_assertion,identity assertion>>* appears.
It can be used to prevent the introduction or removal of _<<_c2pa_assertion,C2PA assertions>>_ (other than the _<<_referenced_assertion,referenced assertions>>_) that could create unintended or unexpected semantics for the overall _<<C2PA Manifest>>._
The method for calculating this field is described in xref:_calculating_the_expected_partial_claim_field[xrefstyle=full].
* `expected_claim_generator` _(optional),_ if present, describes the X.509 certificate of the expected _<<C2PA claim generator>>._
It can be used to avoid creating an unwanted association between the _<<_named_actor,named actor>>_ and an unexpected or undesired _<<C2PA claim generator>>._
The method for calculating this field is described in xref:_calculating_the_expected_claim_generator_field[xrefstyle=full].
* `expected_countersigners` _(optional),_ if present, describes the content of other *<<_identity_assertion,identity assertion>>* in the same _<<C2PA Manifest>>._
The method for calculating this field is described in xref:_calculating_the_expected_countersigners_field[xrefstyle=full].

The *<<_identity_assertion,identity assertion>>* SHALL have a label of `cawg.identity`.

Multiple identity assertions may be used in the same _<<C2PA Manifest>>_ to describe the distinct roles of multiple _<<_actor,actors>>_ in creating a single _<<C2PA asset>>._
This is illustrated in the xref:multiple-identity-assertions[multi-author example] from the conceptual overview.
If this occurs, these assertions SHALL be given unique labels as described by link:++https://spec.c2pa.org/specifications/specifications/2.2/specs/C2PA_Specification.html#_multiple_instances++[Section 6.4, “Multiple instances,”] of the C2PA technical specification.

==== Referenced assertions requirements

The list of _<<_referenced_assertions,referenced assertions>>_ contained in `signer_payload.referenced_assertions` is subject to the following requirements:

* For each assertion listed, an assertion with the same `url`, `alg`, and `hash` values MUST also be listed in the `created_assertions`, `gathered_assertions`, or `assertions` field of either:
** the same _<<C2PA claim>>_ in which the *<<_identity_assertion,identity assertion>>* appears, or
** any _<<C2PA claim>>_ which can be found by recursively tracing the ingredient manifests (as described by link:++https://spec.c2pa.org/specifications/specifications/2.2/specs/C2PA_Specification.html#ingredient_assertion++[Section 18.15, “Ingredient manifests,”] of the C2PA technical specification) of the _<<C2PA claim>>_ in which the *<<_identity_assertion,identity assertion>>* appears.
+
NOTE: The `assertions` field appears only in version 1.x of the C2PA technical specification.
It was replaced with `created_assertions` and `gathered_assertions` in version 2.0 of the C2PA technical specification.

* The list MUST NOT reference any assertion more than once.
* The list MUST include the _<<_hard_binding,hard binding>>_ assertion as described in link:++https://spec.c2pa.org/specifications/specifications/2.2/specs/C2PA_Specification.html#_hard_bindings++[Section 9.2, “Hard bindings,”] of the C2PA technical specification.
This binding MUST be chosen using the approach described in the opening paragraph of link:++https://spec.c2pa.org/specifications/specifications/2.2/specs/C2PA_Specification.html#_validate_the_assets_content++[Section 15.12, “Validate the asset’s content,”] of the C2PA technical specification. This list MUST NOT include a reference to any other _<<_hard_binding,hard binding>>_ assertion.
* The list MAY reference other *<<_identity_assertion,identity assertions>>,* provided that no cycle of references among *<<_identity_assertion,identity assertions>>* is created.

NOTE: The requirement that the `hash` value for a _<<_referenced_assertions,referenced assertion>>_ be known prior to presenting `signer_payload` for signature implies that an *<<_identity_assertion,identity assertion>>* MUST NOT refer to itself.

==== Named actor roles

The _<<_credential_holder,credential holder>>_ MAY choose to describe one or more relationships of the _<<_named_actor,named actor>>_ to the _<<C2PA asset>>_ by adding a `role` field to `signer_payload`.

If present, the value for `role` MUST be a non-empty CBOR array of non-empty text strings.
It is recommended that the CBOR text strings be chosen from the following values and that any user experience that presents the content of an *<<_identity_assertion,identity assertion>>* be prepared to describe these roles in the same human language as the surrounding interface:

[width="100%",cols="4,10",options="header"]
|=======================

| Value
| Meaning

| `cawg.creator`
| The _<<_named_actor,named actor>>_ is a primary creator/author of this _<<C2PA asset>>._

| `cawg.contributor`
| The _<<_named_actor,named actor>>_ is a secondary creator/author of this _<<C2PA asset>>._

| `cawg.editor`
| The _<<_named_actor,named actor>>_ is an editor of this _<<C2PA asset>>._

| `cawg.producer`
| The _<<_named_actor,named actor>>_ is a producer of this _<<C2PA asset>>._

| `cawg.publisher`
| The _<<_named_actor,named actor>>_ is a publisher of this _<<C2PA asset>>._

| `cawg.sponsor`
| The _<<_named_actor,named actor>>_ has supported or sponsored the creation of this _<<C2PA asset>>._

| `cawg.translator`
| The _<<_named_actor,named actor>>_ has adapted of this _<<C2PA asset>>_ from a similar work in another language.

|=======================

Other CBOR text string values MAY be used for `role`, subject to the restrictions described in xref:_labels[xrefstyle=full].
