identity = {
  "signer_payload": $signer-payload-map, ; content to be signed by credential holder
  "signature": bstr, ; byte string of the signature
  ? "trust_registry": trust-registry-map, ; TRQP authorization query and endpoint; see "Trust registry requirements"
  ? "referenced_registry_uri": https-uri, ; URI of a referenced registry; see "Referenced registry" in Terms and definitions
  "pad1": bstr, ; byte string filled with binary `0x00` values used for filling up space
  ? "pad2": bstr, ; optional byte string filled with binary `0x00` values used for filling up space
}

trust-registry-map = {
  "trqp_authorization_uri": https-uri, ; the TRQP-compliant endpoint to query
  "entity_id": tstr .size (1..max-tstr-length), ; the identifier for the entity being tested for authorization
  "authority_id": tstr .size (1..max-tstr-length), ; the identifier for the authority being queried
  "action": tstr .size (1..max-tstr-length), ; the action being checked
  "resource": tstr .size (1..max-tstr-length), ; the resource being checked
}

signer-payload-map = {
  "referenced_assertions": [1* $hashed-uri-map],
  "sig_type": tstr .size (1..max-tstr-length), ; a string identifying the data type of the signature field
  ? "role": [1* (tstr .size (1..max-tstr-length))], ; one or more strings defining the named actor’s relationship(s) to this C2PA asset
  ? "trust_registry_uri": https-uri, ; TO DO: define
}

hash-map = {
  "alg": tstr .size (1..max-tstr-length), ; a string identifying the cryptographic hash algorithm used to compute this hash, taken from the C2PA hash algorithm identifier list
  "hash": bstr, ;  byte string containing the hash value
}

https-uri = tstr .regexp "https://.*"
