==== Verifiable credential proof mechanism

The `signature` field of an *<<_identity_assertion,identity assertion>>* using the identity claim aggregation mechanism MUST be secured using a COSE signature as described by link:++https://www.w3.org/TR/vc-jose-cose/#securing-vcs-with-cose++[Section 3.3.1, “Securing JSON-LD verifiable credentials with COSE,”] of the W3C standard _Securing verifiable credentials using JOSE and COSE._
The `signature` payload MUST begin with the tagged `COSE_Sign1` structure.
As described in that standard, the unsecured verifiable credential is the unencoded `COSE_Sign1` payload.

The COSE signature MAY use a link:https://datatracker.ietf.org/doc/html/rfc3161[RFC 3161]-compliant time stamp to provide an additional, independent signal as to when the _<<_identity_claims_aggregator,identity claims aggregator>>_ generated the *<<_identity_assertion,identity assertion>>.*
If so, this time stamp shall be generated as described by link:++https://spec.c2pa.org/specifications/specifications/2.2/specs/C2PA_Specification.html#_time_stamps++[Section 10.3.2.5, “Time-stamps,”] of the C2PA technical specification.

IMPORTANT: If a time stamp is present, it MUST use a version 2 or later time stamp as defined in link:++https://spec.c2pa.org/specifications/specifications/2.2/specs/C2PA_Specification.html#_choosing_the_payload++[Section 10.3.2.5.2, “Choosing the payload.”]
A version 1 time stamp MUST NOT be used.

If the _<<_identity_claims_aggregator,identity claims aggregator’s>>_ credential supports querying its online credential status, the _<<_identity_claims_aggregator,identity claims aggregator>>_ SHOULD include credential revocation information as described in link:++https://spec.c2pa.org/specifications/specifications/2.2/specs/C2PA_Specification.html#_credential_revocation_information++[Section 10.3.2.6, “Credential revocation information,”] of the C2PA technical specification.

===== Signature algorithms

The COSE signature MUST be secured using one of the signature algorithms defined in link:++https://spec.c2pa.org/specifications/specifications/2.0/specs/C2PA_Specification.html#_digital_signatures++[Section 13.2, “Digital signatures,”] in version 2.2 or any subsequent version of the C2PA technical specification.

===== DID methods

The public key corresponding to the `issuer` field SHALL be discoverable as a `verificationMethod` using a publicly-documented link:++https://www.w3.org/TR/did-core/#dfn-did-methods++[DID method].

As of this writing, a current implementation of an *<<_identity_claims_aggregator,identity claims aggregators>>* uses `did:web`, so it is RECOMMENDED that ICA consumers be prepared to read that method.

Other DID methods MAY be used but implementers are advised that such DIDs may not be widely understood by _<<_identity_assertion_consumer,identity assertion consumers>>._

A future version of this specification will likely align with the forthcoming work of one or both of the following working groups:

* link:https://w3c.github.io/did-methods-wg-charter/2025/did-methods-wg.html[W3C DID Methods Working Group]
* link:https://github.com/decentralized-identity/did-methods[DID method working group at DIF]

Implementers SHOULD consult this section in the current version of this specification when releasing software updates and ensure their supported DID methods conform to it.

===== DID verification methods

The `verificationMethod` containing the `issuer`’s public key SHALL be expressed in the DID document using a publicly-documented DID verification method type.

It is RECOMMENDED that *<<_identity_claims_aggregator,identity claims aggregators>>* use one of the DID verification methods from the list below:

* link:++https://www.w3.org/TR/did-extensions-properties/#jsonwebkey2020++[`JsonWebKey2020`]

Other DID verification methods MAY be used but implementers are advised that such DID documents may not be widely understood by _<<_identity_assertion_consumer,identity assertion consumers>>._

Implementers SHOULD consult this section in the current version of this specification when releasing software updates and ensure their supported DID verification methods conform to it.
