=== Validation method

IMPORTANT: Validation of the _<<C2PA Manifest>>_ MUST be completed with a finding that the manifest is at least _well-formed_ as per link:++https://spec.c2pa.org/specifications/specifications/2.3/specs/C2PA_Specification.html#_well_formed_manifest++[Section 14.3.2, Well-formed manifest,”] of the C2PA technical specification before a validator attempts to report on the validity of an *<<_identity_assertion,identity assertion>>.*

An *<<_identity_assertion,identity assertion>>* MUST contain a valid CBOR data structure that contains the required fields as documented in the `identity` rule in xref:_cbor_schema[xrefstyle=full].
The `cawg.identity.cbor.invalid` error code SHALL be used to report assertions that do not follow this rule.
A validator SHALL NOT consider any extra fields not documented in the `identity` rule during the validation process.

NOTE: Extra fields can be read and processed in non-validation scenarios.

For each entry in `signer_payload.referenced_assertions`, the validator MUST verify that the same entry exists in either the `created_assertions` or `gathered_assertions` entry of the ** the same _<<C2PA claim>>_ in which the *<<_identity_assertion,identity assertion>>* appears, or any _<<C2PA claim>>_ which can be found by recursively tracing the ingredient manifests (as described by link:++https://spec.c2pa.org/specifications/specifications/2.3/specs/C2PA_Specification.html#ingredient_assertion++[Section 18.15, “Ingredient manifests,”] of the C2PA technical specification) of the _<<C2PA claim>>_ in which the *<<_identity_assertion,identity assertion>>* appears.
(For version 1 claims, the entry must appear in the `assertions` entry.)
The `cawg.identity.assertion.mismatch` error code SHALL be used to report violations of this rule.

The validator SHOULD verify that no entry in `signer_payload.referenced_assertions` is duplicated.
The `cawg.identity.assertion.duplicate` error code SHALL be used to report violations of this rule.

The validator MUST ensure that `signer_payload.referenced_assertions` contains a reference to the specific _<<_hard_binding,hard binding>>_ assertion specified using the approach described in the opening paragraph of link:++https://spec.c2pa.org/specifications/specifications/2.3/specs/C2PA_Specification.html#_validate_the_assets_content++[Section 15.12, “Validate the asset’s content,”] of the C2PA technical specification.

The `cawg.identity.hard_binding_missing` error code SHALL be used to report a missing _<<_hard_binding,hard binding>>_ assertion reference.

The `cawg.identity.hard_binding_incorrect` error code SHALL be used to report an incorrect _<<_hard_binding,hard binding>>_ assertion reference.

The validator MUST maintain a list of valid `signer_payload.sig_type` values and corresponding code paths for the `signature` values that it is prepared to accept.
Validators SHOULD be prepared to accept all signature types described in xref:_credentials_signatures_and_validation_methods[xrefstyle=full].
The `cawg.identity.sig_type.unknown` error code SHALL be used to report assertions that contain unrecognized `signer_payload.sig_type` values.

The `signature` field of an *<<_identity_assertion,identity assertion>>* MUST contain a valid signature.
The procedure for validating each signature type and corresponding status codes are described in xref:_credentials_signatures_and_validation_methods[xrefstyle=full].

The `pad1` and `pad2` fields of an *<<_identity_assertion,identity assertion>>* MUST contain only zero-value (`0x00`) bytes.
The `cawg.identity.pad.invalid` error code SHALL be used to report assertions that contain other values in these fields.
