== Credentials, signatures, and validation methods

The *<<_identity_assertion,identity assertion>>* allows multiple signature types to be represented, although only one _<<_verifiable_identifier,verifiable identifier>>_ and corresponding signature can be used in any single assertion.

The signature type is represented by the `signer_payload.sig_type` field.
Some credential types are described in this specification.
It is strongly recommended that *<<_identity_assertion,identity assertion>>* validators be prepared to read all of the signature types described in this specification.

Other specifications MAY define additional `signer_payload.sig_type` values and the corresponding definition of `signature`, subject to restrictions described in xref:_labels[xrefstyle=full].

[IMPORTANT]
.Credential types in minor version updates
====
Future minor version updates (1.1, 1.2, etc.) to this specification MAY:

1. Add new sections to this specification defining new credential types and their corresponding `signer_payload.sig_type` values.
2. Mark existing sections of this specification defining existing credential types and their corresponding `signer_payload.sig_type` values as deprecated.

Such updates to the specification SHOULD continue to use the `cawg.identity` assertion label.
====

[IMPORTANT]
.Network traffic may be required
====
_This section is non-normative._

This section makes use of various credential specifications that require outbound network traffic in order to complete the signature verification process.

An <<_identity_assertion_consumer,identity assertion consumer>> may need to adjust their security posture (e.g. using proxy services when appropriate) to facilitate these requirements.

An <<_identity_assertion_generator,identity assertion generator>> may wish to take steps to mitigate the risks associated with “phone home” calls (i.e. bundling with other, unrelated credential sites).
====

include::identity-claims-aggregation/index.adoc[]

include::x509.adoc[]
