=== X.509 certificates and COSE signatures

In some use cases, an _<<_actor,actor>>_ in the system MAY wish to provide an _https://tools.ietf.org/html/rfc5280[X.509 certificate]_ to have an organizational or individual identity described by the certificate associated with the list of _<<_referenced_assertions,referenced assertions>>._

The `signer_payload.sig_type` value for such an assertion MUST be `cawg.x509.cose`.
The `signature` value MUST be a _https://datatracker.ietf.org/doc/html/rfc8152[COSE signature]_ as described below.

==== Generating the COSE signature

To generate the COSE signature for an *<<_identity_assertion,identity assertion>>,* the steps described in the listed sections of the C2PA technical specification MUST be followed with adaptations as described subsequently:

* link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_signing_a_claim++[Section 10.3.2.4, “Signing a claim”]
* link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_time_stamps++[Section 10.3.2.5, “Time-stamps”]
+
IMPORTANT: An *<<_identity_assertion,identity assertion>>* MUST NOT contain a v1 time-stamp as defined in link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_choosing_the_payload++[Section 10.3.2.5.2, “Choosing the payload.”]
* link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_credential_revocation_information++[Section 10.3.2.6, “Credential revocation information”]
* link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_hashing++[Section 13.1, “Hashing”]
* link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_digital_signatures++[Section 13.2, “Digital signatures”]

In each of the above sections, the following changes MUST be applied:

* Any reference to the _claim_ MUST be replaced with the CBOR serialization of the `signer_payload` field from the *<<_identity_assertion,identity assertion>>.*
The `signer_payload` data structure MUST be serialized as described in link:++https://www.rfc-editor.org/rfc/rfc8949.html#name-core-deterministic-encoding++[Section 4.2.1, “Core Deterministic Encoding,”] of RFC 8949: Concise Binary Object Representation.
The resulting byte string is presented to the _<<_credential_holder,credential holder>>_ for signature.
* Any reference to the _claim generator_ MUST be replaced with the _<<_actor,actor>>_ whose _X.509 certificate_ is being used for this assertion.
* The *<<_identity_assertion,identity assertion>>* generator SHALL use an _X.509 certificate_ that complies with the trust model described in xref:_trust_model_for_x_509_certificates[xrefstyle=full].
* A generator MAY choose to rely on the time-stamp that it expects to be added to the C2PA Claim Signature, or as a separate link:++https://spec.c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#time_stamp_manifests++[C2PA Time-stamp Manifest], instead of adding a separate time-stamp to the <<_identity_assertion,identity assertion>> signature.

==== Validating the COSE signature

To validate the COSE signature for an *<<_identity_assertion,identity assertion>>,* the steps described in the listed sections of the C2PA technical specification MUST be followed with adaptations as described:

* link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_validate_the_signature++[Section 15.5, “Validate the signature.”] Disregard the paragraph that starts with “Retrieve the URI reference.”
Instead retrieve the COSE signature from the `signature` field of the *<<_identity_assertion,identity assertion>>.*
* link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_validate_the_time_stamp++[Section 15.6, “Validate the time-stamp”]
* link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_validate_the_credential_revocation_information++[Section 15.7, “Validate the credential revocation information”]

In each of the above sections, the following changes MUST be applied:

* Any reference to the _claim_ MUST be replaced with the CBOR serialization of the `signer_payload` field from the *<<_identity_assertion,identity assertion>>.*
* Any reference to the _claim generator_ MUST be replaced with the _<<_actor,actor>>_ whose _X.509 certificate_ is being used for this assertion.
* A validator MUST NOT issue the status `cawg.identity.trusted` for an *<<_identity_assertion,identity assertion>>* unless the _X.509 certificate_ is found to comply with the trust model as described in xref:_trust_model_for_x_509_certificates[xrefstyle=full].
* A validator SHALL consider any v1 time-stamp as defined in link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_choosing_the_payload++[Section 10.3.2.5.2, “Choosing the payload”] to be invalid.
* When validating the certificate of the identity assertion signature, the validator SHOULD use the C2PA claim signature link:++https://spec.c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_time_stamps++[time-stamp] or a subsequent link:++https://spec.c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#time_stamp_manifests++[C2PA Time-stamp Manifest] to determine the time of signing, if a time-stamp is not present in the Identity Assertion signature.

==== Trust model for X.509 certificates

A validator shall maintain the following information for evaluating CAWG X.509 signers, known as the *CAWG trust list*:

* A list of accepted Extended Key Usage (EKU) values. For each accepted EKU value,
** A list of accepted Certificate Policy (CP) values.
** A list of X.509 certificate trust anchors.

The list of accepted EKUs MUST include `id-kp-documentSigning` (1.3.6.1.5.5.7.3.36).
No certificate policy or trust anchors are required for `id-kp-documentSigning` at this time.

The trust list requirements for link:++https://spec.c2pa.org/specifications/specifications/2.2/specs/C2PA_Specification.html#_time_stamping_authorities++[Time stamping authorities] and link:++https://spec.c2pa.org/specifications/specifications/2.2/specs/C2PA_Specification.html#_private_credential_storage++[Private credential storage] are identical to those stated in the C2PA technical standard. An implementation MAY share these two trust lists between C2PA and CAWG implementations. Alternatively, it may choose to maintain separate lists for CAWG and C2PA signatures.

[#interim-trust-model]
===== Interim trust model additions

[IMPORTANT]
.Time restrictions for this section
====
The configuration options described in this section are valid only for *identity assertions* generated on or before 31 March 2027.

An *identity assertion* generator MUST include a valid time-stamp in the C2PA manifest or CAWG identity assertion as described in link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_time_stamps++[Section 10.3.2.5, “Time-stamps”], except that a v1 time-stamp as defined in link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_choosing_the_payload++[Section 10.3.2.5.2, “Choosing the payload,”] MUST NOT be used.

An *identity assertion* validator MUST be configured to _verify_ *identity assertions* that were valid at the time of issuance regardless of time of validation.
====

In order to facilitate the use of CAWG identity assertions before fully publicly-governed trust infrastructure that meets all requirements exists, the *CAWG trust list* is extended to include support for S/MIME certificates and specific trust anchor lists able to issue them.
The requirements for such certificates, stated below, are adapted from requirements specified by the CA/Browser Forum in https://cabforum.org/uploads/CA-Browser-Forum-SMIMEBR-1.0.11.pdf[Baseline Requirements for the Issuance and Management of Publicly‐Trusted S/MIME Certificates, version 1.0.11].

The *CAWG trust list* MUST be configured to accept any certificate that meets *all* of the following requirements when used to sign an *identity assertion* issued during the validity window described above.

1. The EKU `id-kp-emailProtection` (1.3.6.1.5.5.7.3.4) is used.
2. One of the following certificate policy IDs is used:
+
** Organization-validated Multipurpose (2.23.140.1.5.2.2)
** Organization-validated Strict (2.23.140.1.5.2.3)
** Sponsor-validated Multipurpose (2.23.140.1.5.3.2)
** Sponsor-validated Strict (2.23.140.1.5.3.3)
** Individual-validated Multipurpose (2.23.140.1.5.4.2)
** Individual-validated Strict (2.23.140.1.5.4.3)
+
IMPORTANT: This list does not include Mailbox-validated or “legacy” certificate purpose OIDs.
3. The certificate chains up to one of the following roots of trust:
+
** The https://wiki.mozilla.org/CA[Mozilla Root Store with the Email (S/MIME) Trust Bit Enabled].
A PEM-encoded version of this list is available at https://ccadb.my.salesforce-sites.com/mozilla/IncludedRootsPEMTxt?TrustBitsInclude=Email.
** The https://iptc.org/verified-news-publishers-list/[IPTC Origin Verified News Publishers List].
A PEM-encoded version of this list is available at https://iptc.org/verified-news-publishers-list/verified-news-publishers-list.pem.
