==== Validating the COSE signature

[NOTE]
====
The procedure described in this section is based on the sections of the C2PA technical specification, version 2.4, titled link:++https://spec.c2pa.org/specifications/specifications/2.4/specs/C2PA_Specification.html#_validate_the_signature++[Section 15.7, “Validate the signature,”] link:++https://spec.c2pa.org/specifications/specifications/2.4/specs/C2PA_Specification.html#_validate_the_time_stamp++[Section 15.8, “Validate the time-stamp,”] and link:++https://spec.c2pa.org/specifications/specifications/2.4/specs/C2PA_Specification.html#_validate_the_credential_revocation_information++[Section 15.9, “Validate the credential revocation information.”]
It has been adapted to operate on the COSE signature contained in an *<<_identity_assertion,identity assertion>>* rather than on a _<<C2PA claim>>_ signature.
====

To validate the COSE signature for an *<<_identity_assertion,identity assertion>>,* the validator MUST follow the procedure described in this section.

[#_x509_validate_the_signature]
===== Validate the signature

The validator MUST retrieve the COSE signature from the `signature` field of the *<<_identity_assertion,identity assertion>>.*

If the signature algorithm is not on the allowed or deprecated list described in link:++https://spec.c2pa.org/specifications/specifications/2.4/specs/C2PA_Specification.html#_digital_signatures++[Section 13.2, “Digital signatures,”] of the C2PA technical specification, then the *<<_identity_assertion,identity assertion>>* MUST be rejected with a failure code of `cawg.x509.algorithm.unsupported`.

Before a chain of trust to a trust anchor is established, the validator MUST first determine if a valid time stamp (as described in xref:_x509_validate_the_time_stamp[xrefstyle=full]) is present.
Then, a chain of trust SHOULD be verified from the credential to a trust anchor configuration in one of the applicable trust anchor lists.
If a `notBefore` date/time is present in a trust anchor configuration, that configuration MUST NOT validate signatures whose time stamp (or current time, if no time stamp is present) is before that date/time.
If a `notAfter` date/time is present, that configuration MUST NOT validate signatures whose time stamp (or current time, if no time stamp is present) is after that date/time.

If a chain of trust cannot be verified, the *<<_identity_assertion,identity assertion>>* MUST be rejected with a failure code of `cawg.x509.credential.untrusted`; otherwise, the *<<_identity_assertion,identity assertion>>* signature MUST be assigned a success code of `cawg.x509.credential.trusted`.

A validator MUST NOT issue the status `cawg.identity.trusted` for an *<<_identity_assertion,identity assertion>>* unless the _X.509 certificate_ is found to comply with the trust model as described in xref:_trust_model_for_x_509_certificates[xrefstyle=full].

If the *<<_identity_assertion,identity assertion>>* has not yet been rejected, validation MUST proceed according to the procedure described in link:++https://spec.c2pa.org/specifications/specifications/2.4/specs/C2PA_Specification.html#_digital_signatures++[Section 13.2, “Digital signatures,”] of the C2PA technical specification.
If validation of the signature fails, the *<<_identity_assertion,identity assertion>>* MUST be rejected with a failure code of `cawg.x509.signature.mismatch`.
Otherwise, the *<<_identity_assertion,identity assertion>>* signature MUST be assigned a success code of `cawg.x509.signature.validated`.

For the remainder of this section, _headers_ refers to the union of the set of protected and unprotected header parameters in the COSE signature.
Unless otherwise specified, a header MAY appear in either bucket.
COSE headers are described in section 3 of https://datatracker.ietf.org/doc/html/rfc8152[RFC 8152].

[#_x509_validate_the_time_stamp]
===== Validate the time-stamp

To determine the validity of an _X.509 certificate_ in an *<<_identity_assertion,identity assertion>>* signature, the validator MUST first consider any time stamp contained within the *<<_identity_assertion,identity assertion>>* itself.
If no such time stamp exists, the validator MUST then evaluate the _<<C2PA claim>>_ signature's link:++https://spec.c2pa.org/specifications/specifications/2.4/specs/C2PA_Specification.html#_time_stamps++[time stamp] or a subsequent link:++https://spec.c2pa.org/specifications/specifications/2.4/specs/C2PA_Specification.html#time_stamp_manifests++[time stamp manifest] or link:++https://spec.c2pa.org/specifications/specifications/2.4/specs/C2PA_Specification.html#timestamp_assertion++[time stamp assertion] to determine the time of signing.

A validator SHALL consider any v1 time stamp (as defined in link:++https://spec.c2pa.org/specifications/specifications/2.4/specs/C2PA_Specification.html#_choosing_the_payload++[Section 10.3.2.5.2, “Choosing the payload,”] of the C2PA technical specification) to be invalid.
Only v2 time stamps, carried in a `sigTst2` header, are acceptable for *<<_identity_assertion,identity assertions>>.*

[#_x509_obtaining_the_timestamptoken]
====== Obtaining the TimeStampToken

If the `sigTst2` header is present in the COSE signature for the *<<_identity_assertion,identity assertion>>,* the `tstTokens` array is expected to contain a single `tstToken`.
If the header contains more than one `tstToken`, the validator MUST issue a `cawg.x509.time_stamp.malformed` informational code and ignore the time stamps.

The validator MUST retrieve the `val` property from the `tstToken`, which MUST be an RFC 3161-compliant `timeStampToken` (TimeStampToken, TST).

If a TimeStampToken obtained from the `sigTst2` header passes validation as per xref:_x509_validating_the_timestamptoken[xrefstyle=full], no further sources need to be considered.
Otherwise, if no `sigTst2` header is present in the *<<_identity_assertion,identity assertion>>* or the TimeStampToken located there did not pass validation, the validator MUST attempt to locate a TimeStampToken from a link:++https://spec.c2pa.org/specifications/specifications/2.4/specs/C2PA_Specification.html#timestamp_assertion++[time-stamp assertion] as described below.

If a validator had previously located any link:++https://spec.c2pa.org/specifications/specifications/2.4/specs/C2PA_Specification.html#timestamp_assertion++[time-stamp assertions] in the _<<C2PA Manifest>>_ Store, maintained in a mapping of _<<C2PA Manifest>>_ identifiers to TimeStampTokens, then the validator MUST check whether the identifier of the _<<C2PA Manifest>>_ that contains the *<<_identity_assertion,identity assertion>>* is present in the mapping.
If it is, the validator MUST use the TimeStampToken associated with that identifier in the validation process described in xref:_x509_validating_the_timestamptoken[xrefstyle=full].
If more than one TimeStampToken for that identifier is found in the mapping, the validator MUST try each one until one successfully passes validation (and then SHOULD ignore the others).
If the identifier does not appear in the mapping, no error is raised, as it simply means that there is no TimeStampToken associated with this _<<C2PA Manifest>>_ in the current context.

[#_x509_validating_the_timestamptoken]
====== Validating the TimeStampToken

The validator MUST continue the process as follows:

* If the signature algorithm in the `timeStampToken` is not on the allowed or deprecated list described in link:++https://spec.c2pa.org/specifications/specifications/2.4/specs/C2PA_Specification.html#_digital_signatures++[Section 13.2, “Digital signatures,”] of the C2PA technical specification, then the validator MUST issue a `cawg.x509.time_stamp.untrusted` informational code and ignore the time stamp.
* Validate the signature in the `timeStampToken`, as described in section 5.6 of https://datatracker.ietf.org/doc/html/rfc2630[RFC 2630].
If the signature is not valid, the validator MUST issue a `cawg.x509.time_stamp.mismatch` informational code and ignore the time stamp.
* If the `timeStampToken` does not contain a `messageImprint` field, the validator MUST issue a `cawg.x509.time_stamp.malformed` informational code and ignore the time stamp.
* If the message imprint hash algorithm is not on the allowed or deprecated list described in link:++https://spec.c2pa.org/specifications/specifications/2.4/specs/C2PA_Specification.html#_hashing++[Section 13.1, “Hashing,”] of the C2PA technical specification, then the validator MUST issue a `cawg.x509.time_stamp.untrusted` informational code and ignore the time stamp.
* Validate that the value of the `messageImprint` field (in the `timeStampToken`) matches the `signature` field of the `COSE_Sign1_Tagged` structure of the *<<_identity_assertion,identity assertion>>* being validated.
If the values do not match, the validator MUST issue a `cawg.x509.time_stamp.mismatch` informational code and ignore the time stamp.
* Validate that the `certificates` field of the `timeStampToken` is present, that the Time Stamping Authority (TSA)’s certificate can be found in the provided set of certificates in this field, and that it is possible to build a trust chain from the TSA’s certificate to an entry in the C2PA TSA Trust List (or other list of trust anchors present in the validator for this purpose).
If the certificate cannot be located or a trust chain cannot be constructed, the validator MUST issue a `cawg.x509.time_stamp.untrusted` informational code and ignore the time stamp.
If the validator determines that a certificate is invalid, it MAY additionally return the informational code `cawg.x509.time_stamp.credential_invalid`.
* Validate that the attested time, as found in the `genTime` field (in the `timeStampToken`), falls within the validity period of the TSA’s signing certificate and all CA certificates up to the trust anchor.
If it does not, the validator MUST issue a `cawg.x509.time_stamp.outside_validity` informational code and ignore the time stamp.
* If time stamp validation does not stop or fail due to any of the above conditions, then the validator MUST issue the success codes `cawg.x509.time_stamp.trusted` and `cawg.x509.time_stamp.validated`.
* If the validator issued both `cawg.x509.time_stamp.trusted` and `cawg.x509.time_stamp.validated` success codes, then the validator MUST validate that the time attested by the TSA, as found in the `genTime` field (in the `timeStampToken`), falls within the validity period of the *<<_identity_assertion,identity assertion>>* signing certificate and all CA certificates up to the trust anchor.
If it does not, the validator MUST reject the *<<_identity_assertion,identity assertion>>* with a `cawg.x509.signature.outside_validity` failure code.

NOTE: Time stamps remain valid even after the signing credential of the Time Stamping Authority expires, so long as the attested time falls within the time stamp authority’s certificate’s validity period. This is a special type of trust extended only to time stamp authorities.

At time of validation, when a time stamp is present, trusted, and validated, the validator MUST use the attested time, and not the current time, when determining the time validity of the signing certificate and the time stamp authority’s certificate.

NOTE: This document does not require that the revocation status of a Time Stamping Authority’s certificate be captured at signing time nor validated at validation time.

If no `sigTst2` header is present in the *<<_identity_assertion,identity assertion>>* and no TimeStampToken can be obtained as described above, or if at least one such time stamp is present but does not satisfy the requirements above, then the *<<_identity_assertion,identity assertion>>* is valid if the current time at validation is within the validity period of the _<<_named_actor,named actor’s>>_ certificate and all CA certificates up to the trust anchor.
If it is, the validator MUST return a success code of `cawg.x509.signature.inside_validity`.
If it is not, the *<<_identity_assertion,identity assertion>>* MUST be rejected with a failure code of `cawg.x509.signature.outside_validity`.

====== Validating the “claimed time of signing”

A validator MAY choose to validate the “claimed time of signing” as attested by the value present in the `iat` protected header.
If the `iat` header is present, the validator MAY validate that the attested time falls within the validity period of the _<<_named_actor,named actor’s>>_ certificate and all CA certificates up to the trust anchor, and not later than the time attested by any associated trusted time stamp.
If the validator does the validation of this value and it falls inside the validity period, the validator MUST return the `cawg.x509.time_of_signing.inside_validity` informational code; if it falls outside the validity period, the validator MUST return the `cawg.x509.time_of_signing.outside_validity` informational code.

[#_x509_validate_the_credential_revocation_information]
===== Validate the credential revocation information

Discovery of the revocation status of the _<<_named_actor,named actor’s>>_ certificate and all CA certificates that are part of the trust chain is important to determining whether a given certificate is considered valid and trusted.

For CA certificates, the validator SHOULD determine revocation status as indicated in the Authority Information Access (AIA) extension as described in section 4.2.2.1 of https://datatracker.ietf.org/doc/html/rfc5280[RFC 5280].
The validator SHOULD make use of relevant OCSP responses included in the _<<C2PA Manifest>>_ if the AIA extension indicates that OCSP is available.

If the validator determines that a CA certificate was revoked at the time indicated in a trusted time stamp, or at the current time if no trusted time stamp is present, then the *<<_identity_assertion,identity assertion>>* MUST be rejected with a failure status of `cawg.x509.credential.untrusted`.

For the _<<_named_actor,named actor’s>>_ certificate, the validator MUST use the following process:

* If a certificate does not support revocation status, or the certificate issuer did not provide a method to query its revocation status, the validator MUST treat the credential as not revoked.
* If the _<<_actor,actor>>_ stapled OCSP responses in the `rVals` header of the `COSE_Sign1` structure of the *<<_identity_assertion,identity assertion>>* signature, the validator MUST decode and validate the stapled OCSP responses as described in xref:_x509_ocsp_stapled[xrefstyle=full].
* If subsequent _<<_actor,actors>>_ added link:++https://spec.c2pa.org/specifications/specifications/2.4/specs/C2PA_Specification.html#certificate_status_assertion++[certificate status assertions] in other _<<_c2pa_manifest,C2PA Manifests>>_ in the _<<C2PA Manifest>>_ Store, the validator MUST use those OCSP responses in the validation process described in xref:_x509_ocsp_stapled[xrefstyle=full].
If more than one OCSP response for the certificate is found, the validator MUST try each one until one successfully passes validation (and then SHOULD ignore the others).

If no revocation information was found in the _<<C2PA Manifest>>_ Store, and the validator is online, then the validator SHOULD attempt to determine the revocation status of the certificate by querying the OCSP responder as described in xref:_x509_ocsp_online[xrefstyle=full].

[#_x509_ocsp_stapled]
====== Determining revocation through OCSP responses in the C2PA Manifest Store

A validator MUST decode OCSP responses per requirements 1 through 4 of section 3.2 of https://datatracker.ietf.org/doc/html/rfc6960[RFC 6960].
If an OCSP response is accepted, and if all of the following requirements are met, then this establishes that the relevant certificate was not revoked at the time of signing:

* The *<<_identity_assertion,identity assertion>>* signature has an attested time provided by a valid signed time stamp.
* There exists a `SingleResponse` in the `responses` array of the `tbsResponseData` field of the OCSP response such that all of the following conditions hold:
** The current time is no earlier than `thisUpdate`.
** The attested time from the time stamp:
*** is earlier than `thisUpdate`, or
*** falls within the `(thisUpdate,nextUpdate)` interval, if `nextUpdate` is present, or
*** falls within the `(thisUpdate,producedAt + 24 hours)` interval, where `producedAt` is the field in the containing `ResponseData`, if `nextUpdate` is not present.
** The `certStatus` field of the `SingleResponse` is `good`.
* The OCSP signer of the response is an “authorized responder” as defined by section 4.2.2.2 of https://datatracker.ietf.org/doc/html/rfc6960[RFC 6960].

Validators MUST check the `revocationReason` of any `revoked` response to disambiguate the `removedFromCRL` case from an actual revocation.

If the above conditions are met for any OCSP response in the _<<C2PA Manifest>>_ Store, then the validator MUST either issue a `cawg.x509.ocsp.not_revoked` success code, indicating that the certificate is considered not revoked at the time of signing, or (for additional assurance) perform an online OCSP check as described in xref:_x509_ocsp_online[xrefstyle=full].

Otherwise, if an OCSP response in the _<<C2PA Manifest>>_ Store meets all of the above conditions except that the `certStatus` field is `revoked`, the certificate MUST be considered revoked and the *<<_identity_assertion,identity assertion>>* MUST be rejected with a `cawg.identity.credential_revoked` failure code.

[#_x509_ocsp_online]
====== Determining revocation from online OCSP response

If, for a given certificate, no OCSP response in the _<<C2PA Manifest>>_ Store satisfies the conditions in xref:_x509_ocsp_stapled[xrefstyle=full], or if the *<<_identity_assertion,identity assertion>>* signature does not have a time stamp, the validator MAY choose to query the OCSP responder per https://datatracker.ietf.org/doc/html/rfc6960[RFC 6960], with the responder `accessLocation` found via section 3.1 of https://datatracker.ietf.org/doc/html/rfc6960[RFC 6960].

NOTE: Querying the credential status method can reveal to an observer the identity of the asset being validated, and so this query is optional.

If the validator chooses not to perform an online OCSP check, it MUST issue a `cawg.x509.ocsp.skipped` informational code.

If the validator attempts to query the OCSP responder but is unable to receive a response, it MUST issue a `cawg.x509.ocsp.inaccessible` informational code.

If a response is received and accepted per requirements 1 through 4 of section 3.2 of https://datatracker.ietf.org/doc/html/rfc6960[RFC 6960], it MUST establish that the _<<_named_actor,named actor’s>>_ certificate was not revoked at the time of signing if either of the following requirements is fulfilled:

* The *<<_identity_assertion,identity assertion>>* signature has a valid time stamp, and the attested time falls within the `(thisUpdate,nextUpdate)` interval of the response, or
* The *<<_identity_assertion,identity assertion>>* signature does not have a valid time stamp but the current real-world time falls within the `(thisUpdate,nextUpdate)` interval of the response,

and both of the following requirements are fulfilled:

* The `certStatus` field of the response is `good`, or `revoked` with a `revocationReason` of `removeFromCRL`, and
* The OCSP signer of the response is an “authorized responder” as defined by section 4.2.2.2 of https://datatracker.ietf.org/doc/html/rfc6960[RFC 6960].

If the `certStatus` field of the response is `revoked` with a `revocationReason` that is not `removeFromCRL`, the response MUST establish that the _<<_named_actor,named actor’s>>_ certificate was not revoked at the time of signing only if both of the following requirements are met:

* The *<<_identity_assertion,identity assertion>>* has a valid time stamp, and the attested time falls within the `(thisUpdate,nextUpdate)` interval of the response, and
* The `revocationTime` in the response is after the attested time stamp.

If the above conditions are met, the certificate MUST be considered not revoked at the time of signing, and the validator MUST issue a `cawg.x509.ocsp.not_revoked` success code.

Otherwise:

* If the `certStatus` field of the response is `unknown`, a `cawg.x509.ocsp.unknown` informational code MUST be recorded.
* Otherwise, the certificate MUST be considered revoked and the *<<_identity_assertion,identity assertion>>* MUST be rejected with a `cawg.identity.credential_revoked` failure code.

===== Status codes

The following status codes are specific to the validation of *<<_identity_assertion,identity assertions>>* whose `signer_payload.sig_type` is `cawg.x509.cose`.
The failure code `cawg.identity.credential_revoked` defined in xref:_status_codes[xrefstyle=full] is also issued by this procedure.

[width="100%",cols="4,4,10",options="header"]
|=======================
| Value
| Status
| Definition

|`cawg.x509.algorithm.unsupported`
| Failure
| The signature algorithm used to sign the *<<_identity_assertion,identity assertion>>* is not on the allowed or deprecated list defined in the C2PA technical specification.

|`cawg.x509.credential.trusted`
| Success
| A chain of trust from the *<<_identity_assertion,identity assertion>>* signing certificate to a trust anchor configuration was verified.

|`cawg.x509.credential.untrusted`
| Failure
| A chain of trust could not be verified from the *<<_identity_assertion,identity assertion>>* signing certificate to any configured trust anchor, or a CA certificate in the chain was determined to be revoked.

|`cawg.x509.signature.validated`
| Success
| The cryptographic signature over the *<<_identity_assertion,identity assertion>>* was validated against the signing certificate.

|`cawg.x509.signature.mismatch`
| Failure
| The cryptographic signature over the *<<_identity_assertion,identity assertion>>* could not be validated against the signing certificate.

|`cawg.x509.signature.inside_validity`
| Success
| No trusted time stamp was available, and the current time at validation falls within the validity period of the _<<_named_actor,named actor’s>>_ certificate and all CA certificates up to the trust anchor.

|`cawg.x509.signature.outside_validity`
| Failure
| The time of signing falls outside the validity period of the _<<_named_actor,named actor’s>>_ certificate or one of the CA certificates up to the trust anchor.

|`cawg.x509.time_stamp.trusted`
| Success
| The Time Stamping Authority’s certificate has a valid chain of trust to a trust anchor in the C2PA TSA Trust List (or other list of trust anchors used by the validator for this purpose).

|`cawg.x509.time_stamp.validated`
| Success
| The signature over the TimeStampToken was validated and all time-stamp validation requirements were met.

|`cawg.x509.time_stamp.malformed`
| Informational
| A time stamp associated with the *<<_identity_assertion,identity assertion>>* is malformed (for example, more than one `tstToken` is present in a `sigTst2` header, or the `messageImprint` field is missing).

|`cawg.x509.time_stamp.mismatch`
| Informational
| The signature over the TimeStampToken did not validate, or the `messageImprint` value did not match the *<<_identity_assertion,identity assertion>>* signature.

|`cawg.x509.time_stamp.untrusted`
| Informational
| The Time Stamping Authority’s certificate could not be located or its chain of trust could not be constructed, or the time stamp uses a signature or hashing algorithm that is not on the allowed or deprecated list.

|`cawg.x509.time_stamp.outside_validity`
| Informational
| The attested time from a time stamp falls outside the validity period of the Time Stamping Authority’s signing certificate or one of the CA certificates up to the trust anchor.

|`cawg.x509.time_stamp.credential_invalid`
| Informational
| A certificate in the Time Stamping Authority’s certificate chain was determined to be invalid.

|`cawg.x509.time_of_signing.inside_validity`
| Informational
| The “claimed time of signing” attested by the `iat` protected header falls within the validity period of the _<<_named_actor,named actor’s>>_ certificate and all CA certificates up to the trust anchor.

|`cawg.x509.time_of_signing.outside_validity`
| Informational
| The “claimed time of signing” attested by the `iat` protected header falls outside the validity period of the _<<_named_actor,named actor’s>>_ certificate or one of the CA certificates up to the trust anchor.

|`cawg.x509.ocsp.not_revoked`
| Success
| The _<<_named_actor,named actor’s>>_ certificate was determined to not be revoked at the time of signing.

|`cawg.x509.ocsp.skipped`
| Informational
| The validator chose not to perform an online OCSP check.

|`cawg.x509.ocsp.inaccessible`
| Informational
| The validator attempted to query an OCSP responder but was unable to receive a response.

|`cawg.x509.ocsp.unknown`
| Informational
| An OCSP response was received, but its `certStatus` field was `unknown`.

|=======================
