==== Validating the COSE signature

[NOTE]
====
The procedure described in this section is based on the sections of the C2PA technical specification, version 2.4, titled link:++https://spec.c2pa.org/specifications/specifications/2.4/specs/C2PA_Specification.html#_validate_the_signature++[Section 15.7, “Validate the signature,”] link:++https://spec.c2pa.org/specifications/specifications/2.4/specs/C2PA_Specification.html#_validate_the_time_stamp++[Section 15.8, “Validate the time-stamp,”] and link:++https://spec.c2pa.org/specifications/specifications/2.4/specs/C2PA_Specification.html#_validate_the_credential_revocation_information++[Section 15.9, “Validate the credential revocation information.”]
It has been adapted to operate on the COSE signature contained in an *<<_identity_assertion,identity assertion>>* rather than on a _<<C2PA claim>>_ signature.
====

To validate the COSE signature for an *<<_identity_assertion,identity assertion>>,* the validator MUST follow the procedure described in this section.

[#_x509_validate_the_signature]
===== Validate the signature

* Any reference to the _claim_ MUST be replaced with the CBOR serialization of the `signer_payload` field from the *<<_identity_assertion,identity assertion>>.*
* Any reference to the _claim generator_ MUST be replaced with the _<<_actor,actor>>_ whose _X.509 certificate_ is being used for this assertion.
* A validator MUST NOT issue the status `cawg.identity.trusted` for an *<<_identity_assertion,identity assertion>>* unless the _X.509 certificate_ is found to comply with the trust model as described in xref:_trust_model_for_x_509_certificates[xrefstyle=full].
* To determine the validity of an _X.509 certificate_ in an *<<_identity_assertion,identity assertion>>* signature, the validator MUST first consider any time stamp contained within the *<<_identity_assertion,identity assertion>>.* If no such time stamp exists, the validator MUST then evaluate the C2PA claim signature’s link:++https://spec.c2pa.org/specifications/specifications/2.4/specs/C2PA_Specification.html#_time_stamps++[time stamp] or a subsequent link:++https://spec.c2pa.org/specifications/specifications/2.4/specs/C2PA_Specification.html#time_stamp_manifests++[time stamp manifest] or link:++https://spec.c2pa.org/specifications/specifications/2.4/specs/C2PA_Specification.html#timestamp_assertion++[time stamp assertion] to determine the time of signing.
* A validator SHALL consider any v1 time stamp as defined in link:++https://spec.c2pa.org/specifications/specifications/2.4/specs/C2PA_Specification.html#_choosing_the_payload++[Section 10.3.2.5.2, “Choosing the payload”] to be invalid.
