=== Other concepts

==== Credential holder

:note-caption: Andrew
NOTE: There can now (and I suspect always could) be more than one actor in control of the identifier. So should at least be "an actor" rather than "the actor", but I suspect we need broader changes.

:note-caption: Note

The _<<_actor,actor>>_ that has control (specifically signature authority) over a _<<_verifiable_identifier,verifiable identifier>>_ that describes a specific _<<_named_actor,named actor>>._

==== Credential revocation

An action signifying that a digital credential can no longer be considered as valid.
This is typically indicated by an action on the part of the credential issuer stating that they can no longer attest to the validity of the information in the credential or an action on the part of the _<<_credential_holder,credential holder>>_ stating that the public/private key pair associated with the credential is no longer valid.

Adapted from link:++https://trustoverip.github.io/ctwg-main-glossary/#term:revocation++[Trust Over IP’s definition of revocation].

==== Identity claims aggregator

:note-caption: Andrew
NOTE: As written, this definition still captures someone who transports in credentials from other places. It also covers a named actor self-signing their VP using a credential from a trusted issuer. It's key to note that under the new model, however, we do not need to trust the identity claims aggregator as long as we trust the credentials they're replaying during the binding action.

:note-caption: Note

An _<<_actor,actor>>_ that collects identity claims (attestations) regarding a _<<_named actor,named actor>>_ from various _<<_identity_provider,identity providers>>_ and can replay those identity claims into *<<_identity assertion,identity assertions>>* on behalf of the _<<_named_actor,named actor>>._
This _<<_actor,actor>>_ MAY be the same as the _<<_identity_assertion_generator,identity assertion generator>>._

==== Identity assertion

:note-caption: Andrew
NOTE: Similar problem discussed in the intro - I'm not a big fan of this definition. They don't necessarily need to "prove control" (e.g. document verification), nor do the referenced assertions have to be produced by them or on their behalf (it's more about an attestation of accuracy). Named actor info like role is also not covered.

:note-caption: Note

A _<<C2PA assertion>>_ that allows a _<<_credential_holder,credential holder>>_ to prove control over a digital identity and bind the identity to a set of _<<_c2pa_assertion,C2PA assertions>>_ produced by them or on their behalf.

==== Identity assertion consumer

A _<<C2PA Manifest Consumer>>_ who also consumes and interprets the content of any *<<_identity_assertion,identity assertions>>* contained within the _<<C2PA Manifest>>._

NOTE: This role can also be thought of as a *relying party* or *verifier* as defined in specifications such as the link:++https://www.w3.org/TR/vc-data-model/#dfn-relying-parties++[W3C verifiable credentials data model].

==== Identity assertion generator

The non-human (hardware or software) _<<_actor,actor>>_ that is responsible for generating the *<<_identity_assertion,identity assertion>>.*
This MAY be the same _<<_actor,actor>>_ as the _<<C2PA claim generator>>._

==== Identity provider

:note-caption: Andrew
NOTE: Interesting that this already covers "the issuer of an identity credential that is used by the _<<identity_assertion_generator,identity assertion generator>>." This shouldn't be possible until VPs are introduced in PR2 due to the lack of C2PA asset binding

:note-caption: Note

An _<<_actor,actor>>_ that is attesting to an identity of the _<<_named_actor,named actor>>_ as understood in the context of the _identity provider._
This _<<actor,actor>>_ MAY be the _<<identity_assertion_generator,identity assertion generator>>,_ a third party contacted by the _<<identity_assertion_generator,identity assertion generator>>,_ or the issuer of an identity credential that is used by the _<<identity_assertion_generator,identity assertion generator>>._

==== Named actor

:note-caption: Andrew
NOTE: I don't think the aprt about the _credential subject_ is true under the identity aggregation model, because you could then say that a "c2paAsset" is a named actor. But under the new model it's much more accurate.

:note-caption: Note

The _<<_actor,actor>>_ whose relationship to a _<<C2PA asset>>_ is documented by an *<<_identity_assertion,identity assertion>>.*
This may also be referred to as a _credential subject_ when identified by the *subject* field of a _<<_verifiable_identifier,verifiable identifier>>._

IMPORTANT: A _named actor_ may be any form of _<<_actor,actor>>,_ including an individual human, an organization of humans, or a non-human (software or hardware device).

IMPORTANT: The _named actor_ is not necessarily the same _<<_actor,actor>>_ as the _<<_credential_holder,credential holder>>,_ though there is an implied trust relationship between the two _<<_actor,actors>>._

==== Natural language string

A sequence of UTF-8 characters that is intended to be displayed to a human user.
When contained within a JSON or CBOR data structure, this may be either:

* a single string object, in which case this string is to be displayed as-is to users, regardless of their expressed language preference, or
* a JSON or CBOR map, in which case the contents should be interpreted as described in link:++https://www.w3.org/TR/vc-data-model/#language-and-base-direction++[§10.1, “Language and base direction,”] of the W3C verifiable credential data model specification.

The string MUST resolve to a non-empty sequence of UTF-8 characters for all supported languages.

==== Placeholder assertion

A temporary _<<C2PA assertion>>_ that is created during _<<C2PA claim>>_ generation which reserves space for the eventual content of the *<<_identity_assertion,identity assertion>>.*
A placeholder assertion MUST be used when the final file layout of the _<<C2PA asset>>_ is required for the _<<_hard_binding,hard binding>>_ assertion, as described in xref:_interaction_with_data_hash_assertion[xrefstyle=full].

==== Referenced assertions

:note-caption: Andrew
NOTE: This is pretty confusing - if the named actor is not always the credential holder, then aren't there instances where the credential holder is not named? Should this just be the named actor instead?
I also don't like the "i.e. authorized by or created by" langauge as previously mentioned.

:note-caption: Note

The set of _<<_c2pa_assertion,C2PA assertions>>_ that are referenced by an *<<_identity_assertion,identity assertion>>* and thus bound to (i.e. authorized by or created by) the _<<_credential_holder,credential holder>>_ named in the *<<_identity_assertion,identity assertion>>.*

==== Trust

In the context of an *<<_identity_assertion,identity assertion>>,* we define _trust_ as meeting or exceeding the minimum level of confidence an _<<_identity_assertion_consumer,identity assertion consumer>>_ requires over assertions made about the identity of the _<<_named_actor,named actor>>_ and the _<<_named_actor,named actor’s>>_ true intention regarding their attestations via content included in and referenced by the *<<_identity_assertion,identity assertion>>.*

==== Trust list

A list of _<<_actor,actors>>,_ published by an authoritative source that are trusted in a specific context.

Adapted from link:++https://trustoverip.github.io/ctwg-main-glossary/#term:trust-list++[Trust Over IP’s definition of trust list].

A _trust list_ can be considered a simplified form of a link:++https://trustoverip.github.io/ctwg-main-glossary/#term:trust-registry++[trust registry].

==== Verifiable identifier

Any credential for which an independent system is able to associate, discover, and verify the cryptographic keys associated with that credential.
