== User experience

_This section is non-normative._

=== Approach

The Creator Assertions Working Group intends, in a forthcoming document, to provide clear recommendations and guidance for implementers of identity-based provenance user experiences (UX).
Similar to the C2PA’s link:https://c2pa.org/specifications/specifications/2.0/ux/UX_Recommendations.html[User experience guidance for implementers], CAWG UX recommendations aim to define best practices for presenting CAWG identity assertions within a _<<_c2pa_manifest,C2PA Manifest>>._
The recommendations strive to describe standard, readily-recognizable experiences that:

* provide _<<named_actors,named actors>>_ a means to express *<<_identity_assertion,identity assertions>>* about a _<<_c2pa_asset,C2PA asset>>,_ and
* provide _<<_identity_assertion_consumer,identity assertion consumers>>_ with additional information about the _<<_c2pa_asset,C2PA asset>>_ they are experiencing, thereby empowering them to understand who is involved in its creation.

CAWG UX recommendations should adhere to the same principles and levels of information disclosure outlined in the link:https://c2pa.org/specifications/specifications/2.0/ux/UX_Recommendations.html[C2PA UX Guidance].

=== Public review, feedback, and evolution

Developing these recommendations is an ongoing process that involves diverse stakeholders, with the results balancing uniformity and familiarity with utility and flexibility for users across contexts, platforms, and devices.
Feedback, review, user testing, and ongoing evolution are key requirements for success.
The recommendations will therefore be an evolving document, informed by real-world experiences deploying CAWG-enabled _<<_c2pa_manifest,C2PA Manifests>>_ across a wide variety of applications and scenarios.
These recommendations will be provided as a companion document.
