[appendix]
== Version history

_This section is non-normative._

*08 January 2026*

* Started 1.3-draft version of this specification, derived from the xref:1.2@ROOT:index.adoc[1.2 version of this specification]. (xref:1.2@ROOT:index.adoc#_version_history[Version history])

*14 January 2026*

* Updated links to point to version 2.3 of C2PA Content Credentials specification.

*02 June 2026*

* Added guidance on outbound network traffic while validating identity assertions.
* Updated links to point to version 2.4 of C2PA Content Credentials specification.
* Removed optional fields `expected_partial_claim`, `expected_claim_generator`, and `expected_countersigners`.

*16 June 2026*

* Introduced definition of _<<_archival_quality_credential,archival-quality credential>>._

*14 July 2026*

* Introduced the _<<_trusted_assertion,trusted assertion>>_ mechanism (CWT + COSE with pre-configured trust anchors), including its credential format, trust model, validation process and status codes, optional claim metadata, and governance.
* Added definitions of _<<_trusted_assertion,trusted assertion>>,_ _<<_trusted_assertion_authority,trusted assertion authority>>,_ _<<_trusted_assertion_authority_registry,trusted assertion authority registry>>,_ and _<<_assertion_claim_type,assertion claim type>>._
