==== Validating KERI signature

To validate the KERI signature on the identity assertion, the following steps MUST be performed:

. Check Signature Type
+
`identity.signer_payload.sig_type` MUST be equal to `cawg.vlei`

. Collect required vLEI metadata

.. Decode `vlei-signature-payload-map`
+
The `identity.signer_payload.signature` field contains CBOR encoded <<vlei-signature-payload-map>> data structure,
which provides the verifier with the most of the metadata required to verify the signature.

.. Sync authorized Public Keys of the Signer
+
Using the `signer_aid` field, check that the KEL of the signer has already been processed and that the keys associated with the establishment event sequence number, as specified in the `kel_seq_num` field, are available.
If not, then use the OOBI URL in the `signer_aid_oobi` field to download and validate the KEL. Abort the process, if KEL is not available, does not contain the required seq number or fails validation.
+
*TODO*: how do we solve a rotated witnesses issue? The URL might not be valid. Possible solutions: copy of a KEL in a well known location, watcher service as a source, make this field an array - one of the URLs will must be kept resolvable then (the witness doesn't have to be current, it just has to respond), some other resolving mechanism for an AID (e.g. DHT, GLEIF API, etc)...

.. Verify Trust Chain
+
NOTE: It is assumed that the following preparation steps have been carried out as a part of the verification's software setup. Schemas of the QVI, LE, OOR and ECR Credentials have been installed. The verifier has obtained and validated the credentials of the issuing QVI(s). See <<vlei_trust_model, vLEI Trust Model>> for a detailed discussion.
+
The following text provides all the mandatory steps that MUST be perfomed in order to verify the Trust Chain. For concisness, the checks that are to be perfomed are described briefly. The term "dependencies" means that a set of credentails must have matching values. For specific dependencies between various vLEI credentials that MUST be validated for each of the used credentials, please refer to the <<vlei_trust_model, vLEI Trust Model>> subsection.
+
*TODO:* define "archival" procedure. How to deal with a credential that was valid at the time of signature but might have been revoked since? Or how to deal with KELs/TELs that are no longer available (e.g. QVI has shutdown, LE is no longer around, etc.)

... Verify LE Credential
+
LE credential contained in the `le_cred` field MUST comply with the GLEIF's LE Credential Schema. Validate dependencies with the QVI credential. Check the status of the credential against the witnesses of the issuing QVI .

... Verify Role Credential
+
If  the `role_cred` field (CBOR sequence) of the <<vlei-signature-payload-map>> is not empty read the `role_cred.cred` value.
The value MUST be a valid JSON and MUST conform to either an OOR Credential Schema or an ECR Credential Schema. To determine the type of the credential check the top level `s` key, it MUST contain the used schema id (e.g. `EEy9PkikFcANV1l7EHukCeXqrzT1hNZjGlUk7wuMO5jw` for an ECR vLEI credential).  If `s` is not present or contains and unknown schema id, abort with an error.

.... Verify OOR Credential
+
Check that `role_cred.cred` is not empty and satisfies the OOR Credential Schema. Validate dependency on the LE credential.Check the status of the credential against the issuing QVI witnesses.

.... Verify ECR Credential
+
Check that `role_cred.cred` is not empty and satisfies the ECR Credential Schema. Validate dependency on the LE credential.Check the status of the credential against the issuing QVI witnesses.
+
.... Verify Role Authorization Credential
OOR credential and ECR credential issued by a QVI require a corresponding role authorizaiton credential. Check that `role_cred.auth_cred` contains the required credential and it conforms to the expected schema, and the dependencies (corresponding values of the QVI, LE and the role credential) match. Section <<vlei_trust_model, vLEI Trust Model>> provides additional details.
+
If the ECR credential was issued by a legal entity (its edges block contains key `le` rather than `auth`) then `role_cred.auth_cred` MUST be an empty string.

. Verify Anchor
+
If `identity.signature.anchor_seq_num` is not empty, the verifier MUST ensure that the AID KEL has a valid event with that sequence number and check that the CESR encoded hash of the serialized `identity.signer_payload` matches one of the values in the `a` field (a list) of this event.


. Verify Signature
+
Serialize `identity.signer_payload` field as specified in the <<Generating the KERI signature>> section.
+
For each CESR encoded signature in the `identity.signature.aid_sig` array perform signature validation against the serialized `signer_payload` binary string. The CESR encoding provides the index of the key used (position in the `k` field in the Establishment Event) and its type (i.e. signature algorithm).
+
The verifier MUST ensure that the weights of keys used add up to the `kt` (key threshold) field value of the Establishment Event specified in `identity.signature.kel_seq_num`.  If `kt` is a list of threshold values, then the weight of each key corresponds to the value at the index (the same as encoded in the signature) of the `kt` field. In this case, the weights MUST add up to at least 1. If `kt` is a number, then this the number of signatures is required. E.g. `kt` is 3, then any three signatures perfomed by the 3 different keys from the `k` list will suffice.
