==== Verifiable credential proof mechanism

The `signature` field of an *<<_identity_assertion,identity assertion>>* using the verifiable credential binding mechanism MUST be secured using a COSE signature as described by the W3C standard _Securing verifiable credentials using JOSE and COSE_ in link:++https://www.w3.org/TR/vc-jose-cose/#securing-vcs-with-cose++[Section 3.3.1, “Securing JSON-LD verifiable credentials with COSE,”] if the _<<_outermost_credential,outermost credential>>_ is a verifiable credential, or in link:++https://www.w3.org/TR/vc-jose-cose/#securing-vps-with-cose++[Section 3.3.2, “Securing JSON-LD verifiable presentations with COSE,”] if the _<<_outermost_credential,outermost credential>>_ is a verifiable presentation.
The `signature` payload MUST begin with the tagged `COSE_Sign1` structure.
As described in that standard, the unsecured verifiable credential or presentation is the unencoded `COSE_Sign1` payload.

The COSE signature MAY use a link:https://datatracker.ietf.org/doc/html/rfc3161[RFC 3161]-compliant time stamp to provide an additional, independent signal as to when the _<<_credential_holder,credential holder>>_ generated the *<<_identity_assertion,identity assertion>>.*
If so, this time stamp shall be generated as described by link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_time_stamps++[Section 10.3.2.5, “Time-stamps,”] of the C2PA technical specification.

IMPORTANT: If a timestamp is present, it MUST use a version 2 or later time-stamp as defined in link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_choosing_the_payload++[Section 10.3.2.5.2, “Choosing the payload.”]
A version 1 time stamp MUST NOT be used.

If any issuer's credential supports querying its online credential status, that issuer SHOULD include credential revocation information as described in link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_credential_revocation_information++[Section 10.3.2.6, “Credential revocation information,”] of the C2PA technical specification.

===== Signature algorithms

The COSE signature MUST be secured using one of the signature algorithms defined in link:++https://c2pa.org/specifications/specifications/2.0/specs/C2PA_Specification.html#_digital_signatures++[Section 13.2, “Digital signatures,”] in version 2.1 or any subsequent version of the C2PA technical specification.

===== DID methods

The public key corresponding to the `holder` field of a verifiable presentation, and any `issuer` field of a verifiable credential SHALL be discoverable as a `verificationMethod` using a publicly-documented link:++https://www.w3.org/TR/did-core/#dfn-did-methods++[DID method].

As of this writing, a current implementation of the *<<_verifiable_credential_binding,verifiable credential binding>>* uses `did:web`, so it is RECOMMENDED that _<<_identity_assertion_consumer,identity assertion consumers>>_ be prepared to read that method.

Other DID methods MAY be used but implementers are advised that such DIDs may not be widely understood by _<<_identity_assertion_consumer,identity assertion consumers>>._

A future version of this specification will likely align with the forthcoming work of one or both of the following working groups:

* link:https://w3c.github.io/did-methods-wg-charter/2025/did-methods-wg.html[W3C DID Methods Working Group]
* link:https://github.com/decentralized-identity/did-methods[DID method working group at DIF]

Implementers SHOULD consult this section in the current version of this specification when releasing software updates and ensure their supported DID methods conform to it.

===== DID verification methods

The `verificationMethod` containing any `holder`'s or `issuer`’s public key SHALL be expressed in the DID document using a publicly-documented DID verification method type.

It is RECOMMENDED that credential issuers and holders use one of the DID verification methods from the list below:

* link:++https://www.w3.org/TR/did-extensions-properties/#jsonwebkey2020++[`JsonWebKey2020`]

Other DID verification methods MAY be used but implementers are advised that such DID documents may not be widely understood by _<<_identity_assertion_consumer,identity assertion consumers>>._

Implementers SHOULD consult this section in the current version of this specification when releasing software updates and ensure their supported DID verification methods conform to it.
