=== Presenting the `signer_payload` data structure for signature

Prior to presenting the _<<_credential_holder,credential holder>>_ with the `signer_payload` data structure for signature, any _<<_referenced_assertions,referenced assertions>>_ that are in the same _<<C2PA claim>>_ as the *<<_identity_assertion, identity assertion>>* MUST themselves be created.
This process is described in link:++https://spec.c2pa.org/specifications/specifications/2.4/specs/C2PA_Specification.html#_creating_assertions++[Section 11.3.1, “Creating assertions,”] of the C2PA technical specification.

The list of _<<_referenced_assertions,referenced assertions>>_ MUST include the _<<_hard_binding,hard binding>>_ assertion that describes the active manifest as described in the opening paragraph of link:++https://spec.c2pa.org/specifications/specifications/2.4/specs/C2PA_Specification.html#_validate_the_assets_content++[Section 16.11, “Validate the asset’s content,”] of the C2PA technical specification.

The list of _<<_referenced_assertions,referenced assertions>>_ SHOULD include any _<<_c2pa_assertion,assertions>>_ necessary to allow the _<<_actor,actor>>_ to accurately describe their relationship to the content.
For example, a `c2pa.actions` assertion could be referenced to attest that the _<<_actor,actor>>_ performed those specific actions.

The `signer_payload` data structure MUST be presented to be signed by the _<<_credential_holder,credential holder>>_ corresponding to each *<<_identity_assertion,identity assertion>>.*
This process is described in more detail in xref:_credentials_signatures_and_validation_methods[xrefstyle=full].

IMPORTANT: If a data hash assertion is being used, the _<<_identity_assertion_generator,identity assertion generator>>_ MUST also follow the process described in xref:_interaction_with_data_hash_assertion[xrefstyle=full].
